server.port: 5560

logging.level:
  root: INFO
  cl.wom: DEBUG
  
app.addition: http://192.168.100.52:5557/addition
app.subtraction: http://192.168.100.52:5558/subtraction
app.multiplication: http://192.168.100.52:5559/multiplication
app.division: http://192.168.100.52:5560/division

trackia.component: DIVISION-1-0
trackia.type: API

trackia.dispatcher.class: TrackiaServerDispatcher
trackia.dispatcher.url: http://localhost:9999/journal
trackia.dispatcher.auth: http://localhost:9999/auth/signin

trackia.dispatcher.email: HELLOWORLD-1-0@trackia.app
trackia.dispatcher.password: 12345678

#Lista de modulos habilitados separados por coma
trackia.modules: SysInfoModule, SlaModule, IndexableModule
